### PR TITLE
Implement Register API

### PR DESCRIPTION
**Pull request by aentinger**
See also [here](https://github.com/107-systems/107-Arduino-Cyphal/pull/203#issuecomment-1418258189).

### CODE REVIEW

**Comment by aentinger** [comment]
Hi @pavel-kirienko :coffee: :wave:

I need a little guidance concerning usage of the Value_1_0 magic **uni**c**o**r**n** :unicorn: .

I currently have the following code structure:

```C++
class RegisterBase {
/* ... */
protected:
  uavcan::_register::Value_1_0 _value;
};
/* ... */
template<typename T>
class RegisterDerivedReadOnly : public RegisterBase
{
public:
  RegisterDerivedReadOnly(std::function<T()> const read_func)
  : RegisterBase{/* ... */}
  , _read_func{read_func}
  { }

  void read() 
  {
    /* It's all about this here: Obviously this doesn't compile as the type returned by _read_func is not a Value_1_0 ... */
    _value.union_value.emplace(_read_func());
  }

private:
  std::function<T()> const _read_func;
};
```
The type (`T`) of `RegisterDerivedReadOnly` can be any of the types supported by `Value_1_0`, i.e. `uavcan::primitive::String_1_0`, `uavcan::primitive::array::Natural8_1_0`, etc.).

**Question**: How do I go about emplacing/storing the value obtained by `_read_func` into `_value`?

**Note**: The full code is available in this PR.

**Comment by pavel-kirienko** [comment]
Exposing the raw DSDL type, `Value_1_0` in this case, is undesirable because it makes the API hard to use. I recommend retaining the type-converting wrapper I shared, it is implemented in `value.cpp` and `value.hpp`; I would say it is an essential part of my implementation. It takes care of the problem you described,

**Comment by aentinger** [comment]
This is just a temporary snapshot, I'll hide away the exposure of `Value_1_0` in the final API.

What I was looking for was rather some nudge in the right direction how to use the `emplace` API in this context :angel: .

**Comment by pavel-kirienko** [comment]
EZ, you need type converters. Like the `Value::set()` method, for instance. Something that accepts the result of your read func and turns it into a `uavcan::_register::Value_1_0`. For example, you could go like:

```c++
    /// Assigns a numerically typed array value (ints, floats, bools, etc.) from multiple scalar arguments.
    /// Dimensionality and type correctness is checked at compile time, so the method cannot fail.
    template <typename... Args>
    auto set(Args&&... args)
        -> std::enable_if_t<(sizeof...(Args) > 0) && std::is_arithmetic_v<std::decay_t<std::common_type_t<Args...>>>>
    {
        using T = std::decay_t<std::common_type_t<Args...>>;
        this->set(std::array<T, sizeof...(Args)>{{static_cast<T>(args)...}});
    }

    /// Assigns a numerically typed array value (ints, floats, bools, etc.) from std::array<>.
    /// Dimensionality and type correctness is checked at compile time, so the method cannot fail.
    template <typename T, std::size_t N>
    auto set(const std::array<T, N>& ar) -> std::enable_if_t<std::is_arithmetic_v<T> && !std::is_same_v<T, bool>>
    {
        const auto once = [&](auto& dst)
        {
            // NOLINTNEXTLINE(bugprone-sizeof-expression)
            static_assert((sizeof(dst.value.elements) / sizeof(dst.value.elements[0])) >= N,
                          "Array would overflow the destination");
            dst.value.count = N;
            std::copy(ar.begin(), ar.end(), std::begin(dst.value.elements));
        };
        // INTEGER  ----------------------------------------
        if constexpr (std::is_same_v<T, std::int64_t>)
        {
            uavcan_register_Value_1_0_select_integer64_(this);
            once(integer64);
        }
        else if constexpr (std::is_same_v<T, std::int32_t>)
        {
            uavcan_register_Value_1_0_select_integer32_(this);
            once(integer32);
        }
        else if constexpr (std::is_same_v<T, std::int16_t>)
        {
            uavcan_register_Value_1_0_select_integer16_(this);
            once(integer16);
        }
        else if constexpr (std::is_same_v<T, std::int8_t>)
        {
            uavcan_register_Value_1_0_select_integer8_(this);
            once(integer8);
        }
        // NATURAL  ----------------------------------------
        else if constexpr (std::is_same_v<T, std::uint64_t>)
        {
            uavcan_register_Value_1_0_select_natural64_(this);
            once(natural64);
        }
        else if constexpr (std::is_same_v<T, std::uint32_t>)
        {
            uavcan_register_Value_1_0_select_natural32_(this);
            once(natural32);
        }
        else if constexpr (std::is_same_v<T, std::uint16_t>)
        {
            uavcan_register_Value_1_0_select_natural16_(this);
            once(natural16);
        }
        else if constexpr (std::is_same_v<T, std::uint8_t>)
        {
            uavcan_register_Value_1_0_select_natural8_(this);
            once(natural8);
        }
        // FLOAT    ----------------------------------------
        else if constexpr (std::is_same_v<T, float>)
        {
            uavcan_register_Value_1_0_select_real32_(this);
            once(real32);
        }
        else if constexpr (std::is_same_v<T, double>)
        {
            uavcan_register_Value_1_0_select_real64_(this);
            once(real64);
        }
        else
        {
            // The expression we feed to static_assert() shall always evaluate to falsity.
            // We can't use a literal false here because the discarded constexpr if branch shall be valid.
            // Details at https://en.cppreference.com/w/cpp/language/if
            static_assert(std::is_void_v<T>,
                          "No known conversion from supplied arguments to register value. "
                          "Consider using explicit type conversion?");
        }
    }

    /// ... see value.hpp
```

**Comment by pavel-kirienko** [comment]
In your specific case you might want to implement the set method like `set(const T&) -> uavcan::_register::Value_1_0`, but I think you really would benefit from adopting value.hpp as-is. If you need help adapting it for C++17, let me know.

**Comment by aentinger** [comment]
Good Morning @pavel-kirienko :coffee: :wave:

Some attempt has been made at 1c33c7a561a88ec35f1dd70a94269788720bc9ee . It fails horribly, see [here](https://github.com/107-systems/107-Arduino-Cyphal/actions/runs/4160298951/jobs/7197160255).

Cause (imho) is that `ar` is of type `std::array<uint8_t>` while `emplace` expects `uavcan::primitive::array::Natural_8_1_0`.

Any advice?

**Comment by pavel-kirienko** [comment]
You should convert your `ar` to `uavcan::primitive::array::Natural_8_1_0` by manually defining suitable conversions. You can do it either by overloading `set()` for every possible argument, or using `if constexpr` as it is done at the moment.

**Comment by aentinger** [comment]
@pavel-kirienko :pray: some help on adjusting this https://github.com/107-systems/107-Arduino-Cyphal/pull/204/commits/8f220723c060141c52e4923be64da28a039003ef#diff-ae62b584dca960822798dadb39b1ddf695bef62ac4491896c8143e4daef99c10R36-R58 .

**Comment by pavel-kirienko** [comment]
Since you've migrated to C++ headers already, you no longer need this particular custom `visit()`; instead, just use `std::visit()` on the Nunuavut-generated type directly.

**Comment by aentinger** [comment]
Handing over to @pavel-kirienko :pray:

**Comment by aentinger** [comment]
Note: Can be built for x86 like this:

```bash
git clone https://github.com/107-systems/107-Arduino-Cyphal && cd 107-Arduino-Cyphal
git checkout reg-api
mkdir build && cd build
cmake -DBUILD_EXAMPLES=ON .. && make
```

**Comment by pavel-kirienko** [comment]
Behold the new register API: [register-api-c++17.tar.gz](https://github.com/107-systems/107-Arduino-Cyphal/files/10912977/register-api-c%2B%2B17.tar.gz). What you need is contained in `include` (the three headers) and `test` (the unit tests; these are based on Catch2 but are trivially convertible to any other framework). To build and test the archive, simply do:

```
mkdir build
cd build
cmake ..
make -j10
./test
```

This implementation requires `cavl.hpp`, please grab it here: https://github.com/pavel-kirienko/cavl/blob/main/c%2B%2B/cavl.hpp

The directory `storage/` contains an optional addition to the register interface: the persistent storage of configuration parameters. This is usually required in embedded systems that utilize Cyphal. The only dependency of this feature is a well-defined key-value non-volatile storage interface (I use LittleFS for this).

**Comment by pavel-kirienko** [comment]
no

**Comment by aentinger** [comment]
Me now merge. The register API doesn't work but is  within grasping distance. Unfortunately this PR has grown way too big. No support for any Arduino platform at the current time -.- .

**Pull request merged**
