### PR TITLE
Implement OpenCyphal Register API for `OpenCyphal-ToF-Distance-Sensor-Node`.

### PR DESCRIPTION
**Pull request by aentinger**
Related to https://github.com/107-systems/l3xz-fw_aux-controller/pull/15 .

### CODE REVIEW

**Comment by generationmake** [comment]
Hello @aentinger 
I have tested the new example. Although I have used a MKR WIFI 1010 because I don't have a MKR ZERO.
Register list and register access works as expected.

But I haven't received any distance data. Do i Have to connect an interrupt line for the TMF8801?
Thanks

**Comment by generationmake** [comment]
Hi @aentinger 
I implemented the uavcan.node.id and uavcan.node.description registers and made them writeable.
I had to make a work around for the node.id register because I think you can't or shouldn't change this register on the fly. But it shows how to implement these registers.
@aentinger could you please look at my changes and check them?
Thanks

**Comment by aentinger** [comment]
Hi @generationmake ☕ 👋 

I'm spending this weekend ⚔️ fighting 😉 . Thank you for furthering the work on the register API 🙇 . Starting tomorrow I'll pick up the ball again. Dynamic port ID configuration is on the roadmap after the register API 👍 .

Cheers, Alex

**Comment by aentinger** [comment]
> But I haven't received any distance data. Do i Have to connect an interrupt line for the TMF8801?

Probably. I think the sketch is not yet adjusted to using the ESLOV connector. Can you check? 🙏 

Re MKR WiFi 1010 or MKR Zero - it does not make a difference, thanks to Arduino. I'm actually running both a MKR 1000 (because it has soldered debug headers available) and a MKR WAN 1310 😉 .

**Comment by generationmake** [comment]
Good morning @aentinger 
The ESLOV connector provides only the Enable-Pin for the TMF8801. The interrupt-line needs to be connected seperately.
I just need to know which pin is used.

**Comment by aentinger** [comment]
Let's take pin **6**. That does not conflict with existing pins and works for the [TMF8801-Basic](https://github.com/107-systems/107-Arduino-TMF8801/blob/main/examples/TMF8801-Basic/TMF8801-Basic.ino) example.

**Comment by aentinger** [comment]
@generationmake with https://github.com/107-systems/107-Arduino-Cyphal/pull/158/commits/a419c0e8786e80664f58325ae7959afa5944f548 you should now be seeing ToF messages at a rate of 10 Hz (if you connnect TMF8801 INT with D6).

**Comment by aentinger** [comment]
Hi @pavel-kirienko :coffee: :wave:

I'd be needing a bit of C++ advise :wink: . In order for my code to work I'd need to retrieve the type of a template class at runtime, in order to perform the [right cast here](https://github.com/107-systems/107-Arduino-Cyphal/blob/b1232bda2aa96491d8758d738f6f1ba6da3e60ef/src/register/RegisterList.h#L95). However, this is made complicated by `-fno-rtti`, no `std::any`, no `std::variant`.

A general feedback on API design would also be appreciated. The API is not yet stable but in a iterative improvement phase where I'll try to narrow down sensible design choices by testing the resulting API in a real-world-example.

**Comment by generationmake** [comment]
Hi @aentinger 
The ToF example is not working.
The CAN or Cyphal functions somehow block the TMF8801 interrupt. As long as CAN is not connected the TMF8801 interrupt works fine and as expected. As soon as CAN is connected and there is data on the CAN bus the TMF8801 is somehow blocked and no more measurements are made. It also won't come back when CAN is disconnected again. You have to reset to make distance measurement work again.

**Comment by aentinger** [comment]
> It also won't come back when CAN is disconnected again.

Probably we should try without interrupt, so basically polling the TMF8801. But this requires some TMF8801 library modification.

Meanwhile, could you complete the missing functions/typedefs for all missing register types?

**Comment by generationmake** [comment]
Hi @aentinger 
I added most missing register types.
I didn't add Real16 because both Real16 and Real32 refer to float and I think this would produce compile errors.
Additionally please check my implementation of register type Bit. I don't know if I did it correctly with the bitpacked array.

**Comment by generationmake** [comment]
> > It also won't come back when CAN is disconnected again.
> 
> Probably we should try without interrupt, so basically polling the TMF8801. But this requires some TMF8801 library modification.

I would prefer to find out why we have an issue with the interrupts.

**Comment by aentinger** [comment]
> Hi @aentinger I added most missing register types.

Looks perfect :+1: Thank you for the effort :bow:

**Comment by generationmake** [comment]
good morning @aentinger 
I just found out that we need a register which describes the type of our distance publication port.
see here:
https://github.com/OpenCyphal/public_regulated_data_types/blob/70573cb98a346f5a9aee54ce421a8a79700df2b4/uavcan/register/384.Access.1.0.dsdl#L103-L199

So I added it to the example.
Maybe we have to discuss the type provided. But it should work for now.

**Comment by aentinger** [comment]
Good Morning @generationmake :coffee: :wave:

String type should work :+1: Thank you! :bow:

**Comment by generationmake** [comment]
Is there a possibility to set the persistent flag? we need this to generate a savable configuration.
see here: https://github.com/OpenCyphal/yakut#node-configuration-example

**Comment by aentinger** [comment]
Good Morning @generationmake :coffee: :wave:

There is now a persistence flag. API has changed again slightly, beware.

**Pull request merged**
