### PR TITLE
Refactor arduino wrapping system (2)

### PR DESCRIPTION
**Pull request by aentinger**
Supersedes #136, rebased on `107-Arduino-UAVCAN:master` and PR against `107-Arduino-UAVCAN:master`.

### CODE REVIEW

**Comment by aentinger** [comment]
I've found another :bug: :wink: 
* When generating the typedefs around service request/response messages CanardTransferKindMessage is wrongly used instead of `CanardTransferKindRequest` and `CanardTransferKindResponse`. Can you please fix this?
```diff
-typedef DSDLBaseType<uavcan_node_ExecuteCommand_Request_1_0, uavcan_node_ExecuteCommand_Request_1_0_SERIALIZATION_BUFFER_SIZE_BYTES_, CanardTransferKindMessage> Request_1_0;
+typedef DSDLBaseType<uavcan_node_ExecuteCommand_Request_1_0, uavcan_node_ExecuteCommand_Request_1_0_SERIALIZATION_BUFFER_SIZE_BYTES_, CanardTransferKindRequest> Request_1_0;
-typedef DSDLBaseType<uavcan_node_ExecuteCommand_Response_1_0, uavcan_node_ExecuteCommand_Response_1_0_SERIALIZATION_BUFFER_SIZE_BYTES_, CanardTransferKindMessage> Response_1_0;
-typedef DSDLBaseType<uavcan_node_ExecuteCommand_Response_1_0, uavcan_node_ExecuteCommand_Response_1_0_SERIALIZATION_BUFFER_SIZE_BYTES_, CanardTransferKindResponse> Response_1_0;
```
Also it would be highly desirable that the namespace has the version number, i.e. `namespace ExecuteCommand_1_0 {` instead of `... Response_1_0`.

**Comment by aentinger** [comment]
Another wish for @moiflo033 :pray: Please invite me as a collaborator to your fork so I can directly push on your branch. That's not possible anymore, now that I opened a new pull request myself :pray:

**Comment by moiflo033** [comment]
Invite sent.

**Comment by pavel-kirienko** [comment]
https://github.com/107-systems/107-Arduino-UAVCAN/pull/136#pullrequestreview-767384836:

>I recall that this is already somewhat handled by nunavut, maybe @pavel-kirienko can advise on a quick remedy for this situation?

Use the `id` filter: https://nunavut.readthedocs.io/en/latest/docs/templates.html#c-filters

Example: https://github.com/UAVCAN/nunavut/blob/a76bfeda30fb15640def41fd940ada552b77ce5d/src/nunavut/lang/c/templates/definitions.j2#L153

Directly inserting identifiers from DSDL into the generated code is unsafe.

**Comment by aentinger** [comment]
Dropping this one for good, see #203 .

**Pull request closed without merging**
