### PR TITLE
Use only `nunavut` generated C++ wrappers instead of C wrappers and manual coded C++ wrappers

### LINKED ISSUE #163: [Feature Request] Add dynamic Subject-IDs
<a href="https://107-systems.org/"></a>

### ⚡ Feature Request

**Please Describe The Problem To Be Solved**
Subject-IDs should be dynamic so that a node can be configured and allow system integration.

### LINKED ISSUE #185: [Feature Request] Automate C++ wrapper generation
<a href="https://107-systems.org/"></a>

### ⚡ Feature Request

Currently the generation of C++ wrappers is done manually. This is tedious, work-intensive and error-prone.

Some work to automatically generate the wrapper files has been started [here](https://github.com/107-systems/107-Arduino-Cyphal/pull/137), but has since come to a stand-still.

Note: While tackling this issue it might make sense to upgrade to generating C++ headers directly.

### PR DESCRIPTION
**Pull request by aentinger**
This fixes #185.

This fixes #163.

### CODE REVIEW

**Comment by aentinger** [comment]
Depends on https://github.com/OpenCyphal/nunavut/issues/271 .

**Comment by aentinger** [comment]
Hi @pavel-kirienko :coffee: :wave: 

I'd like you to take a look at the current state of the re-designed register API. It's not complete, so as of right now you can only read out the list of registers ("list"), but you can't read or write their value ("access"). Nonetheless the basic infrastructure for doing so is in place. Could you please provide some input to steer this effort into the right direction?

**Comment by pavel-kirienko** [comment]
Where exactly should I look? The changeset is very large.

**Comment by aentinger** [comment]
> > Where exactly should I look? The changeset is very large.
> 
> [Here](https://github.com/107-systems/107-Arduino-Cyphal/blob/fix-185/examples/host-example-01-opencyphal-basic-node/host-example-01-opencyphal-basic-node.cpp#L64-L89) and [here](https://github.com/107-systems/107-Arduino-Cyphal/tree/fix-185/src/util/register) 🙏

Ping 😁

**Comment by pavel-kirienko** [comment]
I think this API requires a bit too much attention from the developer to manage properly and is sort of boilerplatey. Also the linear search complexity will be a serious problem for complex applications with over a hundred registers and strict real-time requirements. I recommend another approach that is easier to use and offers a faster logarithmic search. The implementation is here; these four files are part of the same namespace: [src.tar.gz](https://github.com/107-systems/107-Arduino-Cyphal/files/10612058/src.tar.gz)

Tests (sadly this is only a part of the test suite but it's the most important part): [test.tar.gz](https://github.com/107-systems/107-Arduino-Cyphal/files/10612059/test.tar.gz)

The code is written for C++20, but it should be trivial to adapt for C++14. The concepts will have to go, but they are easy to replace with SFINAE helpers from `type_traits`; there might be some other minor dependencies on the standard library which should also be easy to downgrade. The code might not even compile as-is because I just pulled it from a closed-source project and had to introduce a few manual modifications, which could have broken things, but it shouldn't matter because at least the general idea is clear.

The basic idea of the API is that the registers are very fast to query ( $\log{}n$ with `uint64` keys instead of linear search with string comparison --- I expect it to be an order of magnitude faster); the mutability and type are deduced automatically at compilation time. A read-only register is just a callback, and a mutable register is two callbacks (getter and setter). Additionally, there is a helper called `expose()` that can be used to easily share arbitrary states over the network (getter/setter created automatically). The code implemented in `value.hpp` performs automatic type conversion between register types and native types such as arrays; plus, it also handles coercion when the network interface attempts to write a register using a different data type (e.g., int16[] when the register is float64[]).

Here is a usage example, where `rgy` is of type `registry::RegistryImpl`:

```c++
// define a read-only register of type float32[12]
const auto reg = rgy.route("vsi.phase_current_bias",
                           []
                           {
                               return platform::vsi::getDiagnostics().phase_current_bias.value_or(platform::Matrix<3, 4>::Zero());
                           });

// a mutable register of type bool[1]
const auto reg = rgy.route("aux.pull",
                           []
                           {
                               if (const auto val = platform::aux::getStrongPull())
                               {
                                   return static_cast<std::int8_t>(val.value() ? +1 : -1);
                               }
                               return static_cast<std::int8_t>(0);
                           },
                           [](const registry::Value& val)
                           {
                               if (val.get<std::int64_t>().value() > 0)
                               {
                                   platform::aux::setStrongPull(true);
                               }
                               else if (val.get<std::int64_t>().value() < 0)
                               {
                                   platform::aux::setStrongPull(false);
                               }
                               else
                               {
                                   platform::aux::setStrongPull(std::nullopt);
                               }
                               return true;
                           });

// a mutable register created using the exposure helper
float32[7] some_value;
const auto reg = rgy.expose("my.value", registry::Registry::Options{.persistent = true}, some_value);
```

**Comment by aentinger** [comment]
Thank you @pavel-kirienko for your feedback and code-donation 🙇 

I'll be merging this PR since its ballooning out of proportions and opening a new one dealing explicitly with the register API.

**Pull request merged**
