### PR TITLE
Split core Cyphal integration into NodeBase

### PR DESCRIPTION
**Pull request by JustinOng**
Referencing #230, this PR splits the functionality in `Node` into two separate classes while keeping the public API of `Node` unchanged.

The use of `o1heap`, `CircularBufferCan/Fd` now belongs to `Node`, while the other core functionality now belongs to `NodeBase`.

`enqueue_transfer`, `_heap_allocate`(`o1heap_allocate`) and  `_heap_free`(`o1heap_free`) have been marked `virtual` to allow a derived class to wrap these classes with appropriate mutual exclusion mechanisms for use in RTOS applications. Other than ensuring thread-safety, providing this flexibility can also eliminate the need to repeatedly check for time/transmission readiness. (There's probably a conversation to be had here about the performance impact of the heap functions no longer being `static` to allow for a derived class to override it, but that would introduce further complexity to resolve)

An example of this derivation and its use can be found [here](https://github.com/JustinOng/esp-idf-cyphal/blob/master/src/IDFNode.cpp) and [here](https://github.com/JustinOng/esp-idf-cyphal/blob/master/examples/basic/main/main.cpp) respectively.

I would appreciate any feedback/comments on this proposal.

### CODE REVIEW

**Comment by aentinger** [comment]
Hi @JustinOng ☕ 👋 

Thank you for your contribution 🙇 . I'm currently VERY busy and will be so for the next couple of weeks but I'll take a in-depth look at you PR by the end of this month, mkay?

**Review by aentinger — CHANGES_REQUESTED** [review]
Please split more cleanly between transport and non transport-specific code, see also [this comment](https://github.com/107-systems/107-Arduino-Cyphal/pull/236#issuecomment-1611647210).

**Comment by JustinOng** [comment]
Could you elaborate on the dependencies to physical transport layer specific code in the base class that should be separated? There are references to `CAN` throughout, but this is just in name and refers to the I/O of `CanardFrame` to the underlying canard instance. Dropping the name `CAN` is of course trivial to do, but given that libcanard is designed specifically for CAN as a transport, I'm not sure how further this could target generic transports.

**Comment by aentinger** [comment]
Yes, there's also a [libudpard](https://github.com/OpenCyphal-Garage/libudpard) and [libserard](https://github.com/OpenCyphal-Garage/libserard) which provide Cyphal/UDP and Cyphal/Serial. Since those will be eventually incorporated it makes sense to split base/derived along the line of generic/transport layer specific functionality.

Right now base (NodeBase.hpp) contains `CanardInstance`, `CanardTxQueue`, `CanFrameTxFunc ` while derived (Node.hpp) contains `std::shared_ptr<CircularBufferBase> _canard_rx_queue`. That's a kind of strange division, don't you think?

**Comment by JustinOng** [comment]
> That's a kind of strange division, don't you think?

I see your point, but the initial PR was intended to split the "batteries included" part away for the purpose of using other types of batteries.

Regardless, I'm closing this because the proposed changes are not the best way to implement your vision.

**Comment by aentinger** [comment]
> I see your point, but the initial PR was intended to split the "batteries included" part away for the purpose of using other types of batteries.

I get that 👍. But the whole point of the Arduino port is to deliver a "batteries included" version. If you want full configurability you should go for [libcyphal](https://github.com/OpenCyphal-Garage/libcyphal) - alas that's not ready yet. I'd have just ported libcyphal if that would have been possible, but as it was not 107-Arduino-Cyphal became the leading edge of Cyphal/C++ by necessity (not by choice).

Still would like to incorporate your needs into this library as it makes sense overall. The issue right now is time (my own). I'll just tag you in the conversation if/when the effort to make the batteries more exchangeable starts - if that's allright with you?

Cheers, Alex

**Pull request closed without merging**
