### PR TITLE
Update to libcanard:v3.0.0

### PR DESCRIPTION
**Pull request by aentinger**
Depends on https://github.com/107-systems/107-Arduino-MCP2515/pull/58.

Hi @generationmake :coffee: :wave:

Can you please test one (or more) of the examples on hardware?

### CODE REVIEW

**Review by pavel-kirienko — APPROVED** [review]

**Comment by generationmake** [comment]
@aentinger is this library already added to the arduino library manager?

**Comment by aentinger** [comment]
> @aentinger is this library already added to the arduino library manager?

Not yet. Since this is not simply a "add" but a change name/URL the maintainers will have to merge those two (currently open) PRs:

* https://github.com/arduino/library-registry/pull/1489
* https://github.com/arduino/library-registry/pull/1490

Once the library is in the library-index (and available via library manager) I will create a new release containing all the latest changes.

**Comment by generationmake** [comment]
hi @aentinger 
I tested it with
https://github.com/107-systems/l3xz-fw_aux-controller/pull/9
and
https://github.com/107-systems/l3xz-fw_leg-controller/pull/12

both projects were able to compile and a test with the hardware was also successfull!

**Comment by aentinger** [comment]
That's great to know! Thank you for the test!

**Pull request merged**
