### PR TITLE
Provide a UniqueId service to provide a unique ID for the NodeInfo service.

### PR DESCRIPTION
**Pull request by aentinger**

### CODE REVIEW

**Comment by aentinger** [comment]
Hi @generationmake :coffee: :wave:

Care to add support for RP2040? :wink:

**Comment by generationmake** [comment]
Hi @aentinger 
I added some code for the RP2040. It is compiling and seems to be working.
But I fear that there are still some issues. I have tested it with two different boards and both show the same unique id.

**Comment by aentinger** [comment]
Hi @generationmake :coffee: :wave:

Your code should have been working. I've drastically simplified it so as to flush out any remaining bugs, can you please try again?

**Comment by aentinger** [comment]
Unique ID should be now also supported for ESP32. Perhaps @generationmake can give it a try?

**Comment by aentinger** [comment]
Hi @generationmake :coffee: :wave:

Testing the unique id feature has been made as easy as never before. Just use [tools/PrintUniqueId](https://github.com/107-systems/107-Arduino-Cyphal/blob/unique-id/examples/tools/PrintUniqueId/PrintUniqueId.ino).

Can you please check if the unique id service works for ESP32 and Raspberry Pi Pico?

**Pull request merged**
